# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './ui/uiJobContent.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_jobContentDialog(object):
    def setupUi(self, jobContentDialog):
        jobContentDialog.setObjectName("jobContentDialog")
        jobContentDialog.resize(549, 481)
        self.verticalLayout = QtWidgets.QVBoxLayout(jobContentDialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.widget = QtWidgets.QWidget(jobContentDialog)
        self.widget.setObjectName("widget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.verticalLayout.addWidget(self.widget)
        self.textBrowser = QtWidgets.QTextBrowser(jobContentDialog)
        self.textBrowser.setObjectName("textBrowser")
        self.verticalLayout.addWidget(self.textBrowser)
        self.widget_2 = QtWidgets.QWidget(jobContentDialog)
        self.widget_2.setObjectName("widget_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.widget_2)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem2)
        self.copyButton = QtWidgets.QPushButton(self.widget_2)
        self.copyButton.setObjectName("copyButton")
        self.horizontalLayout_2.addWidget(self.copyButton)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem3)
        self.closeButton = QtWidgets.QPushButton(self.widget_2)
        self.closeButton.setObjectName("closeButton")
        self.horizontalLayout_2.addWidget(self.closeButton)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem4)
        self.verticalLayout.addWidget(self.widget_2)

        self.retranslateUi(jobContentDialog)
        QtCore.QMetaObject.connectSlotsByName(jobContentDialog)

    def retranslateUi(self, jobContentDialog):
        _translate = QtCore.QCoreApplication.translate
        jobContentDialog.setWindowTitle(_translate("jobContentDialog", "Content"))
        self.label.setText(_translate("jobContentDialog", "Scraped Content"))
        self.copyButton.setText(_translate("jobContentDialog", "Copy"))
        self.closeButton.setText(_translate("jobContentDialog", "Close"))
