# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './ui/uinewjob.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_NewJobDialog(object):
    def setupUi(self, NewJobDialog):
        NewJobDialog.setObjectName("NewJobDialog")
        NewJobDialog.resize(476, 462)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(NewJobDialog)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.newJobStatusLabel = QtWidgets.QLabel(NewJobDialog)
        self.newJobStatusLabel.setEnabled(False)
        self.newJobStatusLabel.setMaximumSize(QtCore.QSize(16777215, 20))
        self.newJobStatusLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.newJobStatusLabel.setObjectName("newJobStatusLabel")
        self.verticalLayout_2.addWidget(self.newJobStatusLabel)
        spacerItem = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout_2.addItem(spacerItem)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(NewJobDialog)
        self.label.setMinimumSize(QtCore.QSize(70, 0))
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.jobNameField = QtWidgets.QLineEdit(NewJobDialog)
        self.jobNameField.setObjectName("jobNameField")
        self.horizontalLayout.addWidget(self.jobNameField)
        self.eraseJobName = QtWidgets.QPushButton(NewJobDialog)
        self.eraseJobName.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("./ui\\../resources/clear.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.eraseJobName.setIcon(icon)
        self.eraseJobName.setObjectName("eraseJobName")
        self.horizontalLayout.addWidget(self.eraseJobName)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        spacerItem1 = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout_2.addItem(spacerItem1)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.initialJobCheckBox = QtWidgets.QCheckBox(NewJobDialog)
        self.initialJobCheckBox.setObjectName("initialJobCheckBox")
        self.verticalLayout.addWidget(self.initialJobCheckBox)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.urlLabel = QtWidgets.QLabel(NewJobDialog)
        self.urlLabel.setMinimumSize(QtCore.QSize(70, 0))
        self.urlLabel.setObjectName("urlLabel")
        self.horizontalLayout_2.addWidget(self.urlLabel)
        self.urlField = QtWidgets.QLineEdit(NewJobDialog)
        self.urlField.setObjectName("urlField")
        self.horizontalLayout_2.addWidget(self.urlField)
        self.eraseUrl = QtWidgets.QPushButton(NewJobDialog)
        self.eraseUrl.setText("")
        self.eraseUrl.setIcon(icon)
        self.eraseUrl.setObjectName("eraseUrl")
        self.horizontalLayout_2.addWidget(self.eraseUrl)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        spacerItem2 = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout_2.addItem(spacerItem2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.addButotn = QtWidgets.QPushButton(NewJobDialog)
        self.addButotn.setObjectName("addButotn")
        self.horizontalLayout_3.addWidget(self.addButotn)
        self.cancelButton = QtWidgets.QPushButton(NewJobDialog)
        self.cancelButton.setObjectName("cancelButton")
        self.horizontalLayout_3.addWidget(self.cancelButton)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.existJobsArea = QtWidgets.QTextBrowser(NewJobDialog)
        self.existJobsArea.setObjectName("existJobsArea")
        self.verticalLayout_2.addWidget(self.existJobsArea)

        self.retranslateUi(NewJobDialog)
        QtCore.QMetaObject.connectSlotsByName(NewJobDialog)

    def retranslateUi(self, NewJobDialog):
        _translate = QtCore.QCoreApplication.translate
        NewJobDialog.setWindowTitle(_translate("NewJobDialog", "Dialog"))
        self.newJobStatusLabel.setText(_translate("NewJobDialog", "Add New Job"))
        self.label.setText(_translate("NewJobDialog", "Job Name"))
        self.initialJobCheckBox.setText(_translate("NewJobDialog", "Initial Get URL Job"))
        self.urlLabel.setText(_translate("NewJobDialog", "URL"))
        self.addButotn.setText(_translate("NewJobDialog", "Add"))
        self.cancelButton.setText(_translate("NewJobDialog", "Cancel"))
